In [1]:
import pandas as pd
import numpy as np
import mysql.connector as connection

In [2]:
df1 = pd.read_csv("N:/my_projects/credit_card_financial_analysis/Datasets/cc_add.csv")
df1

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,963607849,Blue,300,1,108,31-12-2023,Week-53,Q4,2023,14315.0,690,9603,56,0.048,Swipe,Entertainment,598.69,0
1,932954954,Blue,175,1,96,31-12-2023,Week-53,Q4,2023,5711.0,0,4325,72,0.000,Swipe,Fuel,691.20,0
2,961650885,Blue,195,0,76,31-12-2023,Week-53,Q4,2023,3104.0,1766,9353,24,0.569,Swipe,Travel,216.48,0
3,917695309,Blue,495,1,72,31-12-2023,Week-53,Q4,2023,2553.0,1823,3853,69,0.714,Chip,Grocery,1001.78,0
4,957309271,Blue,100,0,172,31-12-2023,Week-53,Q4,2023,2476.0,1944,4025,65,0.785,Chip,Fuel,845.25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,Blue,100,0,72,31-12-2023,Week-53,Q4,2023,1438.3,0,4928,84,0.000,Online,Grocery,788.48,0
181,962482385,Silver,100,1,150,31-12-2023,Week-53,Q4,2023,34516.0,2052,3510,62,0.059,Swipe,Grocery,772.20,0
182,919695363,Blue,475,1,99,31-12-2023,Week-53,Q4,2023,3807.0,2517,19739,36,0.661,Swipe,Entertainment,504.31,0
183,931822111,Blue,275,0,99,31-12-2023,Week-53,Q4,2023,11548.0,0,7781,72,0.000,Swipe,Food,1167.15,0
184,925168075,Blue,245,1,74,31-12-2023,Week-53,Q4,2023,20769.0,901,1835,43,0.043,Chip,Fuel,201.85,0

In [3]:
df2 = pd.read_csv("N:/my_projects/credit_card_financial_analysis/Datasets/credit_card.csv")
df2

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,01-01-2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,01-01-2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,01-01-2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,01-01-2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,01-01-2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340,1,106,24-12-2023,Week-52,Q4,2023,34516.0,1329,3906,77,0.039,Swipe,Fuel,546.84,0
10104,827703258,Blue,395,1,104,24-12-2023,Week-52,Q4,2023,13426.0,0,4674,66,0.000,Swipe,Grocery,607.62,0
10105,827712108,Blue,125,1,107,24-12-2023,Week-52,Q4,2023,2346.0,1373,4432,72,0.585,Swipe,Bills,797.76,0
10106,827888433,Blue,410,0,96,24-12-2023,Week-52,Q4,2023,6648.0,2242,2089,60,0.337,Swipe,Bills,146.23,0
10107,827890758,Blue,100,0,43,24-12-2023,Week-52,Q4,2023,2062.0,1302,3785,63,0.631,Chip,Bills,1059.80,0

In [4]:
df3 = pd.read_csv("N:/my_projects/credit_card_financial_analysis/Datasets/cust_add.csv")
df3

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,963607849,42,F,3,Uneducated,Married,CA,91750,no,no,yes,cellular,Govt,30574,1
1,932954954,62,F,0,High School,Unknown,NY,91750,yes,no,no,cellular,Selfemployeed,57679,2
2,961650885,47,F,3,Doctorate,Married,NJ,91750,no,no,no,unknown,Blue-collar,152263,1
3,917695309,49,M,5,Graduate,Married,TX,91750,no,no,no,cellular,Businessman,43653,4
4,957309271,53,F,3,Graduate,Married,NY,91750,no,no,no,cellular,Selfemployeed,47883,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,38,M,1,High School,Married,NJ,91750,no,no,no,cellular,Businessman,86104,5
181,962482385,44,F,1,Graduate,Married,CA,91750,yes,no,no,cellular,Retirees,138163,4
182,919695363,52,F,1,Graduate,Single,NJ,91750,yes,no,no,unknown,Selfemployeed,14975,5
183,931822111,36,M,2,Unknown,Single,CA,91750,yes,no,no,cellular,White-collar,107853,5
184,925168075,58,F,2,Graduate,Married,FL,91750,no,yes,no,cellular,Retirees,16680,5

In [5]:
df4 = pd.read_csv("N:/my_projects/credit_card_financial_analysis/Datasets/customer.csv")
df4

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [6]:
df1.isnull().sum()

Client_Num               0
Card_Category            0
Annual_Fees              0
Activation_30_Days       0
Customer_Acq_Cost        0
Week_Start_Date          0
Week_Num                 0
Qtr                      0
current_year             0
Credit_Limit             0
Total_Revolving_Bal      0
Total_Trans_Amt          0
Total_Trans_Ct           0
Avg_Utilization_Ratio    0
Use Chip                 0
Exp Type                 0
Interest_Earned          0
Delinquent_Acc           0
dtype: int64

In [7]:
df2.isnull().sum()

Client_Num               0
Card_Category            0
Annual_Fees              0
Activation_30_Days       0
Customer_Acq_Cost        0
Week_Start_Date          0
Week_Num                 0
Qtr                      0
current_year             0
Credit_Limit             0
Total_Revolving_Bal      0
Total_Trans_Amt          0
Total_Trans_Vol          0
Avg_Utilization_Ratio    0
Use Chip                 0
Exp Type                 0
Interest_Earned          0
Delinquent_Acc           0
dtype: int64

In [8]:
df3.isnull().sum()

Client_Num                 0
Customer_Age               0
Gender                     0
Dependent_Count            0
Education_Level            0
Marital_Status             0
state_cd                   0
Zipcode                    0
Car_Owner                  0
House_Owner                0
Personal_loan              0
contact                    0
Customer_Job               0
Income                     0
Cust_Satisfaction_Score    0
dtype: int64

In [9]:
df4.isnull().sum()

Client_Num                 0
Customer_Age               0
Gender                     0
Dependent_Count            0
Education_Level            0
Marital_Status             0
state_cd                   0
Zipcode                    0
Car_Owner                  0
House_Owner                0
Personal_loan              0
contact                    0
Customer_Job               0
Income                     0
Cust_Satisfaction_Score    0
dtype: int64

In [10]:
df1.dtypes

Client_Num                 int64
Card_Category             object
Annual_Fees                int64
Activation_30_Days         int64
Customer_Acq_Cost          int64
Week_Start_Date           object
Week_Num                  object
Qtr                       object
current_year               int64
Credit_Limit             float64
Total_Revolving_Bal        int64
Total_Trans_Amt            int64
Total_Trans_Ct             int64
Avg_Utilization_Ratio    float64
Use Chip                  object
Exp Type                  object
Interest_Earned          float64
Delinquent_Acc             int64
dtype: object

In [11]:
df1

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,963607849,Blue,300,1,108,31-12-2023,Week-53,Q4,2023,14315.0,690,9603,56,0.048,Swipe,Entertainment,598.69,0
1,932954954,Blue,175,1,96,31-12-2023,Week-53,Q4,2023,5711.0,0,4325,72,0.000,Swipe,Fuel,691.20,0
2,961650885,Blue,195,0,76,31-12-2023,Week-53,Q4,2023,3104.0,1766,9353,24,0.569,Swipe,Travel,216.48,0
3,917695309,Blue,495,1,72,31-12-2023,Week-53,Q4,2023,2553.0,1823,3853,69,0.714,Chip,Grocery,1001.78,0
4,957309271,Blue,100,0,172,31-12-2023,Week-53,Q4,2023,2476.0,1944,4025,65,0.785,Chip,Fuel,845.25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,Blue,100,0,72,31-12-2023,Week-53,Q4,2023,1438.3,0,4928,84,0.000,Online,Grocery,788.48,0
181,962482385,Silver,100,1,150,31-12-2023,Week-53,Q4,2023,34516.0,2052,3510,62,0.059,Swipe,Grocery,772.20,0
182,919695363,Blue,475,1,99,31-12-2023,Week-53,Q4,2023,3807.0,2517,19739,36,0.661,Swipe,Entertainment,504.31,0
183,931822111,Blue,275,0,99,31-12-2023,Week-53,Q4,2023,11548.0,0,7781,72,0.000,Swipe,Food,1167.15,0
184,925168075,Blue,245,1,74,31-12-2023,Week-53,Q4,2023,20769.0,901,1835,43,0.043,Chip,Fuel,201.85,0

In [12]:
df1['Week_Start_Date']=pd.to_datetime(df1['Week_Start_Date'])

C:\Users\nikhi.NIKHILESH\AppData\Local\Temp\ipykernel_19652\2827142736.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df1['Week_Start_Date']=pd.to_datetime(df1['Week_Start_Date'])

In [13]:
df1

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,963607849,Blue,300,1,108,2023-12-31,Week-53,Q4,2023,14315.0,690,9603,56,0.048,Swipe,Entertainment,598.69,0
1,932954954,Blue,175,1,96,2023-12-31,Week-53,Q4,2023,5711.0,0,4325,72,0.000,Swipe,Fuel,691.20,0
2,961650885,Blue,195,0,76,2023-12-31,Week-53,Q4,2023,3104.0,1766,9353,24,0.569,Swipe,Travel,216.48,0
3,917695309,Blue,495,1,72,2023-12-31,Week-53,Q4,2023,2553.0,1823,3853,69,0.714,Chip,Grocery,1001.78,0
4,957309271,Blue,100,0,172,2023-12-31,Week-53,Q4,2023,2476.0,1944,4025,65,0.785,Chip,Fuel,845.25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,Blue,100,0,72,2023-12-31,Week-53,Q4,2023,1438.3,0,4928,84,0.000,Online,Grocery,788.48,0
181,962482385,Silver,100,1,150,2023-12-31,Week-53,Q4,2023,34516.0,2052,3510,62,0.059,Swipe,Grocery,772.20,0
182,919695363,Blue,475,1,99,2023-12-31,Week-53,Q4,2023,3807.0,2517,19739,36,0.661,Swipe,Entertainment,504.31,0
183,931822111,Blue,275,0,99,2023-12-31,Week-53,Q4,2023,11548.0,0,7781,72,0.000,Swipe,Food,1167.15,0
184,925168075,Blue,245,1,74,2023-12-31,Week-53,Q4,2023,20769.0,901,1835,43,0.043,Chip,Fuel,201.85,0

In [14]:
df1.dtypes

Client_Num                        int64
Card_Category                    object
Annual_Fees                       int64
Activation_30_Days                int64
Customer_Acq_Cost                 int64
Week_Start_Date          datetime64[ns]
Week_Num                         object
Qtr                              object
current_year                      int64
Credit_Limit                    float64
Total_Revolving_Bal               int64
Total_Trans_Amt                   int64
Total_Trans_Ct                    int64
Avg_Utilization_Ratio           float64
Use Chip                         object
Exp Type                         object
Interest_Earned                 float64
Delinquent_Acc                    int64
dtype: object

In [15]:
df2

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,01-01-2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,01-01-2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,01-01-2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,01-01-2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,01-01-2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340,1,106,24-12-2023,Week-52,Q4,2023,34516.0,1329,3906,77,0.039,Swipe,Fuel,546.84,0
10104,827703258,Blue,395,1,104,24-12-2023,Week-52,Q4,2023,13426.0,0,4674,66,0.000,Swipe,Grocery,607.62,0
10105,827712108,Blue,125,1,107,24-12-2023,Week-52,Q4,2023,2346.0,1373,4432,72,0.585,Swipe,Bills,797.76,0
10106,827888433,Blue,410,0,96,24-12-2023,Week-52,Q4,2023,6648.0,2242,2089,60,0.337,Swipe,Bills,146.23,0
10107,827890758,Blue,100,0,43,24-12-2023,Week-52,Q4,2023,2062.0,1302,3785,63,0.631,Chip,Bills,1059.80,0

In [16]:
df2['Week_Start_Date']=pd.to_datetime(df2['Week_Start_Date'], format="%d-%m-%Y")

In [17]:
df2

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,2023-01-01,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,2023-01-01,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,2023-01-01,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,2023-01-01,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,2023-01-01,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340,1,106,2023-12-24,Week-52,Q4,2023,34516.0,1329,3906,77,0.039,Swipe,Fuel,546.84,0
10104,827703258,Blue,395,1,104,2023-12-24,Week-52,Q4,2023,13426.0,0,4674,66,0.000,Swipe,Grocery,607.62,0
10105,827712108,Blue,125,1,107,2023-12-24,Week-52,Q4,2023,2346.0,1373,4432,72,0.585,Swipe,Bills,797.76,0
10106,827888433,Blue,410,0,96,2023-12-24,Week-52,Q4,2023,6648.0,2242,2089,60,0.337,Swipe,Bills,146.23,0
10107,827890758,Blue,100,0,43,2023-12-24,Week-52,Q4,2023,2062.0,1302,3785,63,0.631,Chip,Bills,1059.80,0

In [18]:
df3.dtypes

Client_Num                  int64
Customer_Age                int64
Gender                     object
Dependent_Count             int64
Education_Level            object
Marital_Status             object
state_cd                   object
Zipcode                     int64
Car_Owner                  object
House_Owner                object
Personal_loan              object
contact                    object
Customer_Job               object
Income                      int64
Cust_Satisfaction_Score     int64
dtype: object

In [19]:
df3

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,963607849,42,F,3,Uneducated,Married,CA,91750,no,no,yes,cellular,Govt,30574,1
1,932954954,62,F,0,High School,Unknown,NY,91750,yes,no,no,cellular,Selfemployeed,57679,2
2,961650885,47,F,3,Doctorate,Married,NJ,91750,no,no,no,unknown,Blue-collar,152263,1
3,917695309,49,M,5,Graduate,Married,TX,91750,no,no,no,cellular,Businessman,43653,4
4,957309271,53,F,3,Graduate,Married,NY,91750,no,no,no,cellular,Selfemployeed,47883,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,38,M,1,High School,Married,NJ,91750,no,no,no,cellular,Businessman,86104,5
181,962482385,44,F,1,Graduate,Married,CA,91750,yes,no,no,cellular,Retirees,138163,4
182,919695363,52,F,1,Graduate,Single,NJ,91750,yes,no,no,unknown,Selfemployeed,14975,5
183,931822111,36,M,2,Unknown,Single,CA,91750,yes,no,no,cellular,White-collar,107853,5
184,925168075,58,F,2,Graduate,Married,FL,91750,no,yes,no,cellular,Retirees,16680,5

In [20]:
df4.dtypes

Client_Num                  int64
Customer_Age                int64
Gender                     object
Dependent_Count             int64
Education_Level            object
Marital_Status             object
state_cd                   object
Zipcode                     int64
Car_Owner                  object
House_Owner                object
Personal_loan              object
contact                    object
Customer_Job               object
Income                      int64
Cust_Satisfaction_Score     int64
dtype: object

In [21]:
df4

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [22]:
df2.columns

Index(['Client_Num', 'Card_Category', 'Annual_Fees', 'Activation_30_Days',
       'Customer_Acq_Cost', 'Week_Start_Date', 'Week_Num', 'Qtr',
       'current_year', 'Credit_Limit', 'Total_Revolving_Bal',
       'Total_Trans_Amt', 'Total_Trans_Vol', 'Avg_Utilization_Ratio',
       'Use Chip', 'Exp Type', 'Interest_Earned', 'Delinquent_Acc'],
      dtype='object')

In [23]:
df1.columns

Index(['Client_Num', 'Card_Category', 'Annual_Fees', 'Activation_30_Days',
       'Customer_Acq_Cost', 'Week_Start_Date', 'Week_Num', 'Qtr',
       'current_year', 'Credit_Limit', 'Total_Revolving_Bal',
       'Total_Trans_Amt', 'Total_Trans_Ct', 'Avg_Utilization_Ratio',
       'Use Chip', 'Exp Type', 'Interest_Earned', 'Delinquent_Acc'],
      dtype='object')

In [24]:
df1

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,963607849,Blue,300,1,108,2023-12-31,Week-53,Q4,2023,14315.0,690,9603,56,0.048,Swipe,Entertainment,598.69,0
1,932954954,Blue,175,1,96,2023-12-31,Week-53,Q4,2023,5711.0,0,4325,72,0.000,Swipe,Fuel,691.20,0
2,961650885,Blue,195,0,76,2023-12-31,Week-53,Q4,2023,3104.0,1766,9353,24,0.569,Swipe,Travel,216.48,0
3,917695309,Blue,495,1,72,2023-12-31,Week-53,Q4,2023,2553.0,1823,3853,69,0.714,Chip,Grocery,1001.78,0
4,957309271,Blue,100,0,172,2023-12-31,Week-53,Q4,2023,2476.0,1944,4025,65,0.785,Chip,Fuel,845.25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,Blue,100,0,72,2023-12-31,Week-53,Q4,2023,1438.3,0,4928,84,0.000,Online,Grocery,788.48,0
181,962482385,Silver,100,1,150,2023-12-31,Week-53,Q4,2023,34516.0,2052,3510,62,0.059,Swipe,Grocery,772.20,0
182,919695363,Blue,475,1,99,2023-12-31,Week-53,Q4,2023,3807.0,2517,19739,36,0.661,Swipe,Entertainment,504.31,0
183,931822111,Blue,275,0,99,2023-12-31,Week-53,Q4,2023,11548.0,0,7781,72,0.000,Swipe,Food,1167.15,0
184,925168075,Blue,245,1,74,2023-12-31,Week-53,Q4,2023,20769.0,901,1835,43,0.043,Chip,Fuel,201.85,0

In [25]:
df2

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,2023-01-01,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,2023-01-01,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,2023-01-01,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,2023-01-01,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,2023-01-01,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340,1,106,2023-12-24,Week-52,Q4,2023,34516.0,1329,3906,77,0.039,Swipe,Fuel,546.84,0
10104,827703258,Blue,395,1,104,2023-12-24,Week-52,Q4,2023,13426.0,0,4674,66,0.000,Swipe,Grocery,607.62,0
10105,827712108,Blue,125,1,107,2023-12-24,Week-52,Q4,2023,2346.0,1373,4432,72,0.585,Swipe,Bills,797.76,0
10106,827888433,Blue,410,0,96,2023-12-24,Week-52,Q4,2023,6648.0,2242,2089,60,0.337,Swipe,Bills,146.23,0
10107,827890758,Blue,100,0,43,2023-12-24,Week-52,Q4,2023,2062.0,1302,3785,63,0.631,Chip,Bills,1059.80,0

In [26]:
df1.rename(columns={'Total_Trans_Ct': 'Total_Trans_Vol'}, inplace=True)

In [27]:
df1

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,963607849,Blue,300,1,108,2023-12-31,Week-53,Q4,2023,14315.0,690,9603,56,0.048,Swipe,Entertainment,598.69,0
1,932954954,Blue,175,1,96,2023-12-31,Week-53,Q4,2023,5711.0,0,4325,72,0.000,Swipe,Fuel,691.20,0
2,961650885,Blue,195,0,76,2023-12-31,Week-53,Q4,2023,3104.0,1766,9353,24,0.569,Swipe,Travel,216.48,0
3,917695309,Blue,495,1,72,2023-12-31,Week-53,Q4,2023,2553.0,1823,3853,69,0.714,Chip,Grocery,1001.78,0
4,957309271,Blue,100,0,172,2023-12-31,Week-53,Q4,2023,2476.0,1944,4025,65,0.785,Chip,Fuel,845.25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,964474458,Blue,100,0,72,2023-12-31,Week-53,Q4,2023,1438.3,0,4928,84,0.000,Online,Grocery,788.48,0
181,962482385,Silver,100,1,150,2023-12-31,Week-53,Q4,2023,34516.0,2052,3510,62,0.059,Swipe,Grocery,772.20,0
182,919695363,Blue,475,1,99,2023-12-31,Week-53,Q4,2023,3807.0,2517,19739,36,0.661,Swipe,Entertainment,504.31,0
183,931822111,Blue,275,0,99,2023-12-31,Week-53,Q4,2023,11548.0,0,7781,72,0.000,Swipe,Food,1167.15,0
184,925168075,Blue,245,1,74,2023-12-31,Week-53,Q4,2023,20769.0,901,1835,43,0.043,Chip,Fuel,201.85,0

In [28]:
df2

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,2023-01-01,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,2023-01-01,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,2023-01-01,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,2023-01-01,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,2023-01-01,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340,1,106,2023-12-24,Week-52,Q4,2023,34516.0,1329,3906,77,0.039,Swipe,Fuel,546.84,0
10104,827703258,Blue,395,1,104,2023-12-24,Week-52,Q4,2023,13426.0,0,4674,66,0.000,Swipe,Grocery,607.62,0
10105,827712108,Blue,125,1,107,2023-12-24,Week-52,Q4,2023,2346.0,1373,4432,72,0.585,Swipe,Bills,797.76,0
10106,827888433,Blue,410,0,96,2023-12-24,Week-52,Q4,2023,6648.0,2242,2089,60,0.337,Swipe,Bills,146.23,0
10107,827890758,Blue,100,0,43,2023-12-24,Week-52,Q4,2023,2062.0,1302,3785,63,0.631,Chip,Bills,1059.80,0

In [29]:
credit_card_df = pd.concat([df2,df1], ignore_index=True)
credit_card_df

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,2023-01-01,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,2023-01-01,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,2023-01-01,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,2023-01-01,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,2023-01-01,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10288,964474458,Blue,100,0,72,2023-12-31,Week-53,Q4,2023,1438.3,0,4928,84,0.000,Online,Grocery,788.48,0
10289,962482385,Silver,100,1,150,2023-12-31,Week-53,Q4,2023,34516.0,2052,3510,62,0.059,Swipe,Grocery,772.20,0
10290,919695363,Blue,475,1,99,2023-12-31,Week-53,Q4,2023,3807.0,2517,19739,36,0.661,Swipe,Entertainment,504.31,0
10291,931822111,Blue,275,0,99,2023-12-31,Week-53,Q4,2023,11548.0,0,7781,72,0.000,Swipe,Food,1167.15,0
10292,925168075,Blue,245,1,74,2023-12-31,Week-53,Q4,2023,20769.0,901,1835,43,0.043,Chip,Fuel,201.85,0

In [30]:
df3.columns

Index(['Client_Num', 'Customer_Age', 'Gender', 'Dependent_Count',
       'Education_Level', 'Marital_Status', 'state_cd', 'Zipcode', 'Car_Owner',
       'House_Owner', 'Personal_loan', 'contact', 'Customer_Job', 'Income',
       'Cust_Satisfaction_Score'],
      dtype='object')

In [31]:
df4.columns

Index(['Client_Num', 'Customer_Age', 'Gender', 'Dependent_Count',
       'Education_Level', 'Marital_Status', 'state_cd', 'Zipcode', 'Car_Owner',
       'House_Owner', 'Personal_loan', 'contact', 'Customer_Job', 'Income',
       'Cust_Satisfaction_Score'],
      dtype='object')

In [32]:
customers_df = pd.concat([df4,df3], ignore_index=True)
customers_df

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10288,964474458,38,M,1,High School,Married,NJ,91750,no,no,no,cellular,Businessman,86104,5
10289,962482385,44,F,1,Graduate,Married,CA,91750,yes,no,no,cellular,Retirees,138163,4
10290,919695363,52,F,1,Graduate,Single,NJ,91750,yes,no,no,unknown,Selfemployeed,14975,5
10291,931822111,36,M,2,Unknown,Single,CA,91750,yes,no,no,cellular,White-collar,107853,5
10292,925168075,58,F,2,Graduate,Married,FL,91750,no,yes,no,cellular,Retirees,16680,5

In [33]:
credit_card_df.to_csv("final_credit_card.csv", index=False)

In [34]:
customers_df.to_csv("final_customers.csv", index=False)